version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: echo 'export PATH=/bin:$PATH' >> $BASH_ENV
      - run: git config --global user.email developement@seocraft.net
      - run: git config --global user.name "TomateDeveloper"
      - run: sh waterfall build